version: '3.7'

services:

  api:
    build:
      context: .
      dockerfile: "Dockerfile"
    environment:
      ConnectionStrings__Redis: "redis"
    ports:
      - "5000:80"
    depends_on:
      - "redis"

  redis:
    image: redis
